# Generated by Django 3.2.11 on 2022-01-25 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20220125_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='date_of_dearth',
            new_name='date_of_death',
        ),
    ]
