# Generated by Django 4.1.4 on 2022-12-08 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_date'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
